export const projects = [
  {
    id: "1",
    title: "netflix-clone",
    by: "react",
    img: "https://i.ibb.co/sFZFJ00/Netflix-clone.png",
    desc: "This project is a complete training to do a copy of the original Netflix site,so it is a responsive web design and use Firebase to save users data, log in and out and save favorite movies.",
    technologies: ["react", "redux toolkit", "firebase", "tailwindcss"],
    repo: "https://github.com/Yasser-Tarek-1/netflix-clone",
    live: "https://netflix-clone-phi-blue.vercel.app",
  },
  {
    id: "2",
    title: "e-commerce",
    by: "react",
    img: "https://i.ibb.co/h7tPhrM/E-commerce-app.png",
    desc: "It is an online store based on fake data from Fakestoreapi website and built by styled-components and Redux toolKit and responsive.",
    technologies: ["react", "redux toolkit", "styled-components"],
    repo: "https://github.com/Yasser-Tarek-1/e-commerce",
    live: "https://e-commerce-henna-phi.vercel.app/",
  },
  {
    id: "3",
    title: "quiz-app",
    by: "react",
    img: "https://i.ibb.co/qjPhGwt/New-quiz.png",
    desc: "It is a quick test application consisting of four sections, questions that the person chooses, as well as choosing the number of questions, using data from opentdb website.",
    technologies: ["react", "tailwindcss"],
    repo: "https://github.com/Yasser-Tarek-1/quiz-app",
    live: "https://quiz-app-gamma-kohl.vercel.app/",
  },
  {
    id: "4",
    title: "weather-app",
    by: "react",
    img: "https://i.ibb.co/dbVzpLd/New-wheather.png",
    desc: "An idea for a weather app that uses data from openweathermap website. ",
    technologies: ["react", "redux toolkit", "tailwindcss"],
    repo: "https://github.com/Yasser-Tarek-1/weather-app",
    live: "https://weather-app-zeta-gilt.vercel.app/",
  },
  {
    id: "5",
    title: "admin-dashboard",
    by: "react",
    img: "https://i.ibb.co/ZhfHF0K/Admin-dashboard.png",
    desc: "This is a simple project that uses Firebase to create a dashboard and has the ability to log in and out and display users data.",
    technologies: ["react", "redux toolkit", "sass", "firebase"],
    repo: "https://github.com/Yasser-Tarek-1/dashboard",
    live: "https://dashboard-eta-black.vercel.app/",
  },
];
