import React, { useEffect, useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { projects } from "../../projects";

import Image from "next/image";
import Link from "next/link";

import { RiRadioButtonFill } from "react-icons/ri";

import FourOhFour from "../404";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";

const Project = () => {
  const router = useRouter();
  const path = router.asPath.slice(10);

  const [pro, setPro] = useState({});

  useEffect(() => {
    let data = projects.filter((item) => {
      return item.title === path;
    });
    setPro(...data);
  }, [path]);

  return (
    <>
      {Object.keys(pro || {}).length > 0 ? (
        <>
          <Navbar />
          <div className="w-full min-h-[calc(100vh-140px)]">
            <Head>
              <title>Yasser | Front-End Developer</title>
              <meta name="description" content="Generated by create next app" />
              <meta
                name="viewport"
                content="width=device-width, initial-scale=1.0"
              />
              <link rel="icon" href="/logo.ico" />
            </Head>
            <div className="w-full h-[40vh] relative">
              <Image
                src={pro?.img}
                alt="/"
                className="w-full absolute top-0 left-0 object-cover"
                layout="fill"
                objectFit="cover"
              />
              <div className="absolute top-0 left-0 w-full h-full bg-black/40 z-20" />
              <div className="container mx-auto p-4 w-full relative h-full">
                <div className="absolute z-30 top-[80%] w-full left-[50%] right-[50%] translate-x-[-50%] translate-y-[-50%] px-4 text-white/75">
                  <h2 className="py-2 capitalize">{pro?.title}</h2>
                </div>
              </div>
            </div>
            <div className="container mx-auto p-4 w-full">
              <div className="grid md:grid-cols-5 gap-8 pt-4">
                <div className="col-span-4">
                  <p className=" font-bold uppercase py-2 text-lg text-[#5651e5]">
                    Project
                  </p>
                  <h2>Overview</h2>
                  <p className="py-2 text-gray-600 max-w-[750px]">
                    {pro?.desc}
                  </p>
                  <Link href={pro ? pro.repo : ""} target="_blank">
                    <a target="_blank">
                      <button className="px-5 py-2 mt-4 mr-3 sm:mr-6 capitalize rounded-full">
                        Github Repo
                      </button>
                    </a>
                  </Link>
                  <Link href={pro ? pro.live : ""} target="_blank">
                    <a target="_blank">
                      <button className="px-4 py-2 mt-4 capitalize rounded-full">
                        View Demo
                      </button>
                    </a>
                  </Link>
                </div>
                <div className="col-span-4 lg:col-span-1 shadow-xl shadow-gray-400 p-4 rounded-xl">
                  <div className="p-2 ">
                    <p className="text-center font-bold text-lg py-2">
                      Technologies
                    </p>
                    <div className="grid grid-cols-2 lg:grid-cols-1">
                      {pro?.technologies.map((item) => {
                        return (
                          <>
                            <p className="flex items-center font-semibold text-gray-500 py-2 capitalize">
                              <span className="mr-2">
                                <RiRadioButtonFill />
                              </span>
                              {item}
                            </p>
                          </>
                        );
                      })}
                    </div>
                  </div>
                </div>
              </div>
              <Link href="/#projects">
                <p className="underline cursor-pointer mt-8 w-fit">Back</p>
              </Link>
            </div>
          </div>
          <Footer />
        </>
      ) : (
        <FourOhFour />
      )}
    </>
  );
};

export default Project;
