import React from "react";

import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import { RiRadioButtonFill } from "react-icons/ri";

import creativeImg from "../../public/assets/projects/creative.png";

const creative = () => {
  return (
    <div className="w-full min-h-[calc(100vh-140px)]">
      <Head>
        <title>Yasser | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-[40vh] relative">
        <Image
          src={creativeImg}
          alt="/"
          className="w-full absolute top-0 left-0"
          layout="fill"
          objectFit="cover"
        />
        <div className="absolute top-0 left-0 w-full h-full bg-black/80 z-20" />
        <div className="container mx-auto p-4 w-full relative h-full">
          <div className="absolute z-30 top-[80%] w-full left-[50%] right-[50%] translate-x-[-50%] translate-y-[-50%] px-4 text-white/75    ">
            <h2 className="py-2">Landing Page</h2>
            <p>Html / css</p>
          </div>
        </div>
      </div>
      <div className="container mx-auto p-4 w-full">
        <div className="grid md:grid-cols-5 gap-8 pt-4">
          <div className="col-span-4">
            <p className=" font-bold uppercase py-2 text-lg text-[#5651e5]">
              Project
            </p>
            <h2>Overview</h2>
            <p className="py-2 text-gray-600">
              This app was built using Pure Html and Css. One of the first
              projects I designed to learn and master the basics,It`s just one
              page of fake data.
            </p>
            <Link
              href="https://github.com/Yasser-Tarek-1/creative-design"
              target="_blank"
            >
              <a target="_blank">
                <button className="px-5 py-2 mt-4 mr-3 sm:mr-6 capitalize rounded-full">
                  Github Repo
                </button>
              </a>
            </Link>
            <Link
              href="https://creative-design-lyart.vercel.app/"
              target="_blank"
            >
              <a target="_blank">
                <button className="px-5 py-2 mt-4 capitalize rounded-full">
                  View Demo
                </button>
              </a>
            </Link>
          </div>
          <div className="col-span-4 lg:col-span-1 shadow-xl shadow-gray-400 p-4 rounded-xl">
            <div className="p-2 ">
              <p className="text-center font-bold text-lg py-2">Technologies</p>
              <div className="grid grid-cols-2 lg:grid-cols-1">
                <p className="flex items-center font-semibold text-gray-500 py-2">
                  <span className="mr-2">
                    <RiRadioButtonFill />
                  </span>
                  Html
                </p>
                <p className="flex items-center font-semibold text-gray-500 py-2">
                  <span className="mr-2">
                    <RiRadioButtonFill />
                  </span>
                  css
                </p>
              </div>
            </div>
          </div>
        </div>
        <Link href="/#projects">
          <p className="underline cursor-pointer mt-8 w-fit">Back</p>
        </Link>
      </div>
    </div>
  );
};

export default creative;
