import Link from "next/link";
import Head from "next/head";

function FourOhFour() {
  return (
    <div className="absolute top-[50%] left-[50%] translate-y-[-50%] translate-x-[-50%] w-full ">
      <Head>
        <title>Yasser | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <h1 className="text-center text-2xl sm:text-4xl">404 - Page Not Found</h1>
      <div className="w-fit m-auto mt-5 underline">
        <Link href="/">
          <a>Go back home</a>
        </Link>
      </div>
    </div>
  );
}
export default FourOhFour;
